inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.7
  DisabledByDefault: true
  DisplayCopNames: true
  Exclude:
    - "db/**/*"
    - "script/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "bin/*"
    - "storage/**/*"

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Exclude:
    - "spec/system/data_migration/*"

Metrics/AbcSize:
  Exclude:
    - "app/mailers/tigerdata_mailer.rb"

Metrics/BlockLength:
  Exclude:
    - "app/models/mediaflux/http/asset_create_request.rb"
    - "config/environments/**/*"
    - "lib/tasks/**/*"
    - "spec/**/*"
  Max: 40 # default: 25

Metrics/ClassLength:
  Max: 150 # default: 100
  Exclude:
    - app/models/media_flux_client.rb

Metrics/MethodLength:
  Max: 15 # default: 10
  Exclude:
    - app/models/media_flux_client.rb
    - "app/mailers/tigerdata_mailer.rb"

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Exclude: []

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Rails/UnknownEnv:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - "spec/views/**/*"
    - "spec/system/**/*"

RSpec/ExampleLength:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
