---
version: 2.1
jobs:
  build: # name of your job
    working_directory: ~/tiger_data
    machine: # executor type
      image: ubuntu-2004:202010-01 # recommended linux image - includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4
      docker_layer_caching: true
    steps:
      - checkout
      - run: echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin 
      - run:
            name: Start all services declared in docker-compose.yml
            command: docker-compose build && docker-compose up -d
      - run:
            name: Database migrations
            command: docker exec -it tiger_data_rails_1 bundle exec rails db:migrate
      - run:
            name: Create tigerdata schema in Mediaflux
            command: docker exec -it tiger_data_rails_1 bundle exec rake schema:create RAILS_ENV=development 
      - run:
            name: Run tests
            command: docker exec -it tiger_data_rails_1 bundle exec rspec spec