---
version: 2.1
jobs:
  build: # name of your job
    machine: # executor type
      image: default
      docker_layer_caching: true
    steps:
      - checkout
      - run: echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin 
      - run:
            name: Start all services declared in docker-compose.yml
            command: docker-compose build && docker-compose up -d
      - run:
            name: Database migrations
            command: docker exec -it project-rails-1 bundle exec rails db:migrate
      - run:
            name: Create tigerdata schema in Mediaflux
            command: docker exec -it project-rails-1 bundle exec rake schema:create RAILS_ENV=development 
      - run:
            name: Run tests
            command: docker exec -it project-rails-1 bundle exec rspec spec