---
production:
  - bs3097 # Bess Sadler
  - cac9 # Carolyn Cole
  - cbentler # Chuck Bentler
  - cl7359 # Claudia Lee
  - fn8243 # Favour Nwogbo
  - hc8719 # Hector Correa
  - jrg5 # James Griffin
  - knight # Robert Knight
  - kl37 # Kate Lynch
  - mjc12 # Matt Chandler
  - rl3667 # Robert-Anthony Lee-Faison
  - jh6441 # Jaymee Hyppolite
qa:
  - bs3097 # Bess Sadler
  - cac9 # Carolyn Cole
  - cbentler # Chuck Bentler
  - cl7359 # Claudia Lee
  - fn8243 # Favour Nwogbo
  - hc8719 # Hector Correa
  - jrg5 # James Griffin
  - knight # Robert Knight
  - kl37 # Kate Lynch
  - mjc12 # Matt Chandler
  - rl3667 # Robert-Anthony Lee-Faison
  - jh6441 # Jaymee Hyppolite
staging:
  - bs3097 # Bess Sadler
  - cac9 # Carolyn Cole
  - cbentler # Chuck Bentler
  - cl7359 # Claudia Lee
  - fn8243 # Favour Nwogbo
  - hc8719 # Hector Correa
  - jrg5 # James Griffin
  - knight # Robert Knight
  - kl37 # Kate Lynch
  - mjc12 # Matt Chandler
  - rl3667 # Robert-Anthony Lee-Faison
  - jh6441 # Jaymee Hyppolite
development:
  - bs3097 # Bess Sadler
  - cac9 # Carolyn Cole
  - cbentler # Chuck Bentler
  - cl7359 # Claudia Lee
  - fn8243 # Favour Nwogbo
  - hc8719 # Hector Correa
  - jrg5 # James Griffin
  - kl37 # Kate Lynch
  - rl3667 # Robert-Anthony Lee-Faison
  - jh6441 # Jaymee Hyppolite
test:
  - fake1 # Fake user for testing
