---
production:
  api_root_ns: <%= ENV["MEDIAFLUX_ROOT_NS"] || '/td-prod-001' %>
  api_transport: <%= ENV["MEDIAFLUX_TRANSPORT"] || 'https' %>
  api_host: <%= ENV["MEDIAFLUX_HOST"] %>
  api_port: <%= ENV["MEDIAFLUX_PORT"] || 443 %>
  api_domain: <%= ENV["MEDIAFLUX_DOMAIN"] %>
  api_user: <%= ENV["MEDIAFLUX_USER"] %>
  api_password: <%= ENV["MEDIAFLUX_PASSWORD"] %>
qa:
  api_root_ns: <%= ENV["MEDIAFLUX_ROOT_NS"] || '/td-qa-001' %>
  api_transport: <%= ENV["MEDIAFLUX_TRANSPORT"] || 'https' %>
  api_host: <%= ENV["MEDIAFLUX_HOST"] %>
  api_port: <%= ENV["MEDIAFLUX_PORT"] || 443 %>
  api_domain: <%= ENV["MEDIAFLUX_DOMAIN"] %>
  api_user: <%= ENV["MEDIAFLUX_USER"] %>
  api_password: <%= ENV["MEDIAFLUX_PASSWORD"] %>
development:
  api_root_ns: <%= '/td-staging-001'  %>
  api_transport: <%= 'https' %>
  api_host: <%= 'td-meta1.princeton.edu' %>
  api_port: <%= 443 %>
  api_domain: <%= 'system' %>
  api_user: <%= 'manager' %>
  api_password: <%= 'change_me' %>
test:
  api_root_ns: '/td-test-001'
  api_transport: 'http'
  api_host: 'mediaflux.example.com'
  api_port: '8888'
  api_domain: 'system'
  api_user: 'manager'
  api_password: 'change_me'
