---
production:
  api_root_ns: <%= ENV["MEDIAFLUX_ROOT_NS"] || '/td-prod-001/tigerdataNS' %>
  api_root_collection: <%= ENV["MEDIAFLUX_ROOT_COLLECTION"] || 'path=/td-prod-001/tigerdata' %>
  api_root_collection_name: <%= ENV["MEDIAFLUX_ROOT_COLLECTION"] || 'tigerdata' %>
  api_root_collection_namespace: '/td-prod-001'
  api_transport: <%= ENV["MEDIAFLUX_TRANSPORT"] || 'https' %>
  api_host: <%= ENV["MEDIAFLUX_HOST"] %>
  api_port: <%= ENV["MEDIAFLUX_PORT"] || 443 %>
  api_domain: <%= ENV["MEDIAFLUX_DOMAIN"] %>
  api_user: <%= ENV["MEDIAFLUX_USER"] %>
  api_password: <%= ENV["MEDIAFLUX_PASSWORD"] %>
  shared_files_location: <%= ENV["SHARED_FILES_MOUNT"] || '/mnt/nfs/tigerdata' %>
qa:
  api_root_ns: <%= ENV["MEDIAFLUX_ROOT_NS"] || '/td-qa-001/tigerdataNS' %>
  api_root_collection_name: 'tigerdata'
  api_root_collection_namespace: '/td-qa-001'
  api_root_collection: <%= ENV["MEDIAFLUX_ROOT_NS"] || 'path=/td-qa-001/tigerdata' %>
  api_transport: <%= ENV["MEDIAFLUX_TRANSPORT"] || 'https' %>
  api_host: <%= ENV["MEDIAFLUX_HOST"] %>
  api_port: <%= ENV["MEDIAFLUX_PORT"] || 443 %>
  api_domain: <%= ENV["MEDIAFLUX_DOMAIN"] %>
  api_user: <%= ENV["MEDIAFLUX_USER"] %>
  api_password: <%= ENV["MEDIAFLUX_PASSWORD"] %>
  shared_files_location: <%= ENV["SHARED_FILES_MOUNT"] || '/mnt/nfs/tigerdata' %>
staging:
  api_root_ns: <%= ENV["MEDIAFLUX_ROOT_NS"] || '/td-staging-001/tigerdataNS'  %>
  api_root_collection_name: 'tigerdata'
  api_root_collection_namespace: '/td-staging-001'
  api_root_collection: <%= ENV["MEDIAFLUX_ROOT_NS"] || 'path=/td-staging-001/tigerdata'  %>
  api_transport: <%= ENV["MEDIAFLUX_TRANSPORT"] || 'https' %>
  api_host: <%= ENV["MEDIAFLUX_HOST"] %>
  api_port: <%= ENV["MEDIAFLUX_PORT"] || 443 %>
  api_domain: <%= ENV["MEDIAFLUX_DOMAIN"] %>
  api_user: <%= ENV["MEDIAFLUX_USER"] %>
  api_password: <%= ENV["MEDIAFLUX_PASSWORD"] %>
  shared_files_location: <%= ENV["SHARED_FILES_MOUNT"] || '/mnt/nfs/tigerdata' %>
development:
  api_root_ns: <%= ENV["MEDIAFLUX_ROOT_NS"] || '/td-demo-001/tigerdataNS' %>
  api_root_collection_name: 'tigerdata'
  api_root_collection_namespace: '/td-demo-001'
  api_root_collection: <%= ENV["MEDIAFLUX_ROOT_NS"] || 'path=/td-demo-001/tigerdata' %>
  api_transport: <%= ENV["MEDIAFLUX_TRANSPORT"] || 'http' %>
  api_host: <%= ENV["MEDIAFLUX_HOST"] || '0.0.0.0' %>
  api_port: <%= ENV["MEDIAFLUX_PORT"] || '8888' %>
  api_domain: <%= ENV["MEDIAFLUX_DOMAIN"] || 'system' %>
  api_user: <%= ENV["MEDIAFLUX_USER"] || 'manager' %>
  api_password: <%= ENV["MEDIAFLUX_PASSWORD"] || 'change_me' %>
  shared_files_location: <%= ENV["SHARED_FILES_MOUNT"] || './public/' %>
test:
  api_root_ns: <%= ENV["MEDIAFLUX_ROOT_NS"] || '/td-demo-001/tigerdataNS' %>
  api_root_collection_name: 'tigerdata'
  api_root_collection_namespace: '/td-test-001'
  api_root_collection: <%= ENV["MEDIAFLUX_ROOT_NS"] || 'path=/td-demo-001/tigerdata' %>
  api_transport: <%= ENV["MEDIAFLUX_TRANSPORT"] || 'http' %>
  api_host: <%= ENV['MEDIAFLUX_HOST'] || '0.0.0.0' %>
  api_port: <%= ENV["MEDIAFLUX_PORT"] || '8888' %>
  api_domain: <%= ENV["MEDIAFLUX_DOMAIN"] || 'system' %>
  api_user: <%= ENV["MEDIAFLUX_USER"] || 'manager' %>
  api_password: <%= ENV["MEDIAFLUX_PASSWORD"] || 'change_me' %>
  shared_files_location: <%= ENV["SHARED_FILES_MOUNT"] || './public/' %>
