production: &production
  host: <%= ENV['TIGER_DATA_REDIS_URL'] || 'localhost' %>
  port: <%= ENV['TIGER_DATA_REDIS_PORT'] || '6379' %>
  db: <%= ENV['TIGER_DATA_REDIS_DB'] || 0 %>
staging:
  <<: *production
